version: 2

sources:
  - name: stg
    database: rare-guide-433209-e6   
    schema: AdAccounts_stg               # Updated schema to AdAccounts_stg
    tables:
      - name: LLA_Hubspot_Leads      
        identifier: LLA_Hubspot_Leads     
        description: "Staging table for Hubspot Leads data loaded via App Script."

      - name: LLA_FacebookAds
        identifier: LLA_FacebookAds
        description: "Staging table for Facebook Ads data loaded via App Script."

      - name: LLA_GoogleAds
        identifier: LLA_GoogleAds
        description: "Staging table for Google Ads data loaded via App Script."

      - name: LLA_TikTokAds
        identifier: LLA_TikTokAds
        description: "Staging table for TikTok Ads data loaded via App Script."

      - name: LLA_YouTubeAds
        identifier: LLA_YouTubeAds
        description: "Staging table for YouTube Ads data loaded via App Script."

      - name: Rio_Hubspot_Leads      
        identifier: Rio_Hubspot_Leads  
        description: "Staging table for Hubspot Leads data loaded via App Script."

      - name: Rio_FacebookAds
        identifier: Rio_FacebookAds
        description: "Staging table for Facebook Ads data loaded via App Script."

      - name: Rio_GoogleAds
        identifier: Rio_GoogleAds
        description: "Staging table for Google Ads data loaded via App Script."

      - name: Rio_YouTubeAds
        identifier: Rio_YouTubeAds
        description: "Staging table for YouTube Ads data loaded via App Script."
